server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
    address-shuffle-mode:
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key