spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/address
    password: 1
    username: postgres

  application:
    name: employee-service
server:
  port: 8080
  servlet:
    context-path: /employee-service

feign:
  client:
    config:
      employee-service:
        connect-timeout: 5000

message:
  queue:
    "employee-queue"
  exchange:
    "employee-exchange"
  routingKey:
    "employee-routingKey"
  shipping:
    "employee-shipping"
  message_only_shipping:
    "for-only-shipping"


