spring:
  application:
    name: address-service
  datasource:
    url: jdbc:postgresql://localhost:5432/address
    password: 1
    username: postgres

server:
  port: 8089
  servlet:
    context-path: /address-service
feign:
  client:
    config:
      address-service:
        connect-timeout: 5000